blank_issues_enabled: false
contact_links:
  - name: Outlook
    url: rohan.bharatia@outlook.com
  - name: GMail
    url: rohanbharatia100@gmail.com
  - name: GitHub
    url: https://github.com/Rohan-Bharatia