name: Linux Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake python3 libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

      - name: Verify dependencies
        run: |
          cmake --version
          python3 --version
          g++ --version

      - name: Run
        run: chmod +x ./Build.sh && ./Build.sh
