name: CMake Build and Test w/ MinGW

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          choco install cmake mingw
          cmake --version
          gcc --version

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" ..

      - name: Build Nautilus
        run: |
          cd build
          cmake --build .

      - name: Test Nautilus
        run: |
          cd build
          ctest
